apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo
    targetRevision: HEAD
    path: k8s-manifests/rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: test-rollback
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  # Hooks for pre/post sync operations
  # These are referenced in the hook yaml files
