apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: test-rollback
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: myapp
